name: pio-run

on:
  push:
    branches:
      main
  workflow_dispatch:

jobs:
  test:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ["works", "doesnt"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: |
        pip install platformio
        platformio upgrade --dev
    - run: |
        platformio run -e ${{ matrix.env }}
